env:
  global:
    - CC_TEST_REPORTER_ID=ecb753423174dbd8e4aaf04fb62bf4ef9c2a54904ac49a33fdf2b908b3c5e5f3

sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4

before_install: gem install bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
