name: Test
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * MON'

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test-rails:
    name: 'Test the gem (Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }})'
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        rails: ['8.0', '8.1']
    env:
      BUNDLE_GEMFILE: 'gemfiles/rails_${{ matrix.rails }}.gemfile'
    steps:
      - name: Prepare the environment
        uses: hausgold/actions/ci@v2
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: ci/gem-test

      - name: Install the correct Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: '3.7.2'

      - name: Run the gem tests
        run: make test

      - name: Upload the code coverage report
        run: coverage

  test-grape:
    name: 'Test the gem (Ruby ${{ matrix.ruby }}, Grape ${{ matrix.grape }})'
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        grape: ['1', '2', '3']
    env:
      BUNDLE_GEMFILE: 'gemfiles/grape_${{ matrix.grape }}.gemfile'
    steps:
      - name: Prepare the environment
        uses: hausgold/actions/ci@v2
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: ci/gem-test

      - name: Install the correct Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: '3.7.2'

      - name: Run the gem tests
        run: make test

      - name: Upload the code coverage report
        run: coverage
